name: "Increment Helm Chart Version"
description: "Reads the Helm chart version from Chart.yaml, increments the patch version, and outputs the new version."

inputs:
  chart_path:
    description: "Path to the directory containing the Helm chart (default: 'charts')"
    default: 'charts'
outputs:
  new_version:
    description: "The incremented version of the Helm chart."
runs:
  using: "docker"
  image: "docker://node:20"
  args:
    - bash
    - -c
    - |
      set -e
      # Validate input
      if [[ -z "$INPUT_CHART_PATH" ]]; then
        echo "Error: chart_path input is required."
        exit 1
      fi

      # Locate the Chart.yaml file
      CHART_FILE=$(find "$INPUT_CHART_PATH" -name "Chart.yaml" | head -n 1)

      if [[ -z "$CHART_FILE" ]]; then
        echo "Error: Chart.yaml not found in the specified path: $INPUT_CHART_PATH"
        exit 1
      fi

      echo "Found Chart file: $CHART_FILE"

      # Extract the current version
      CURRENT_VERSION=$(grep '^version:' "$CHART_FILE" | awk '{print $2}')
      echo "Current version: $CURRENT_VERSION"

      if [[ -z "$CURRENT_VERSION" ]]; then
        echo "Error: No version found in $CHART_FILE"
        exit 1
      fi

      # Increment the patch version
      IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
      PATCH=$((PATCH + 1))
      NEW_VERSION="$MAJOR.$MINOR.$PATCH"
      echo "New version: $NEW_VERSION"

      # Set the output
      echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
