name: "Argo Workflow Executor"
description: "Submit Argo workflows with specific parameters"
inputs:
  argo_workflow_file:
    type: string
    description: "Path to the Argo workflow file"
    required: true
  parameters:
    type: array
    description: "list of parameters to pass to the workflow in format paramKey=paramValue"
    required: true
  argo_namespace:
    type: string
    description: "namespace where the Argo workflow will be submitted"
    default: "argo-events"
  branch:
    type: string
    description: "git branch value for the pipeline, defaults to ${GITHUB_REF_NAME}"
    default: ""
outputs:
  result:
    description: "Result of the workflow execution"
runs:
  using: "docker"
  image: "docker://quay.io/vrozsypalek/argoworkflow-cli:v3.5.8-debian"
  args:
     - /bin/bash
     - -c
     - |
       argo submit /github/workspace/${{ inputs.argo_workflow_file }} --namespace=${{ inputs.argo_namespace }} --generate-name=${GITHUB_REPOSITORY#*/}-argo-submit-${GITHUB_SHA_SHORT}- -p appName=${GITHUB_REPOSITORY#*/} -p branch=${{ inputs.branch || github.ref_name }} -p shortSha=${GITHUB_SHA:0:5} -p appOrg=${GITHUB_REPOSITORY%%/*} --parameter=${{ join(fromJSON(inputs.parameters),' --parameter=') }} --wait --log
